package Wsdl2Code.WebServices.ServiceProviderBinding;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 10/22/2015 8:44:42 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import Wsdl2Code.WebServices.ServiceProviderBinding.AppointmentXml;
import Wsdl2Code.WebServices.ServiceProviderBinding.VectorCustomerSurveyResultXml;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class CustomerSurveyXml implements KvmSerializable {
    
    public AppointmentXml appointment;
    public VectorCustomerSurveyResultXml customerSurveyResults;
    public String date;
    public boolean dateSpecified;
    public String id;
    public int status;
    public boolean statusSpecified;
    
    public CustomerSurveyXml(){}
    
    public CustomerSurveyXml(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Appointment"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Appointment");
            appointment =  new AppointmentXml (j);
            
        }
        if (soapObject.hasProperty("CustomerSurveyResults"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("CustomerSurveyResults");
            customerSurveyResults = new VectorCustomerSurveyResultXml(j);
        }
        if (soapObject.hasProperty("Date"))
        {
            Object obj = soapObject.getProperty("Date");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                date = j.toString();
            }else if (obj!= null && obj instanceof String){
                date = (String) obj;
            }
        }
        if (soapObject.hasProperty("DateSpecified"))
        {
            Object obj = soapObject.getProperty("DateSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                dateSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                dateSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("Id"))
        {
            Object obj = soapObject.getProperty("Id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                id = j.toString();
            }else if (obj!= null && obj instanceof String){
                id = (String) obj;
            }
        }
        if (soapObject.hasProperty("Status"))
        {
            Object obj = soapObject.getProperty("Status");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                status = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                status = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("StatusSpecified"))
        {
            Object obj = soapObject.getProperty("StatusSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                statusSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                statusSpecified = (Boolean) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return appointment;
            case 1:
                return customerSurveyResults;
            case 2:
                return date;
            case 3:
                return dateSpecified;
            case 4:
                return id;
            case 5:
                return status;
            case 6:
                return statusSpecified;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 7;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = AppointmentXml.class;
                info.name = "Appointment";
                break;
            case 1:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "CustomerSurveyResults";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Date";
                break;
            case 3:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "DateSpecified";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Id";
                break;
            case 5:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "Status";
                break;
            case 6:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "StatusSpecified";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
